INSERT INTO CATEGORIA (ID, NOMBRE , IMAGEN) VALUES (1,'Backend',null);
INSERT INTO CATEGORIA (ID, NOMBRE , IMAGEN) VALUES (2,'Bases de datos',null);
INSERT INTO CATEGORIA (ID, NOMBRE , IMAGEN) VALUES (3,'Big data',null);
INSERT INTO CATEGORIA (ID, NOMBRE, IMAGEN) VALUES (4,'Blockchain',null);


INSERT INTO PRODUCTO (ID, NOMBRE, DESCRIPCION, IMAGEN, CATEGORIA_ID) VALUES (5, "API Rest con Node JS y Express: JWT y ficheros", "En este curso aprenderemos a crear una API Rest usando Node.js y Expres.js, así como a añadir el sistema JWT y subida de ficheros.", "https://dc722jrlp2zu8.cloudfront.net/media/academy/course/nodejs-card.jpg", 1);
INSERT INTO PRODUCTO (ID, NOMBRE, DESCRIPCION, IMAGEN, CATEGORIA_ID) VALUES (6, "Desarrollo web con Java EE", "Con este curso aprenderás a construir aplicaciones web avanzadas con tecnología Java, utilizando para ello el ecosistema Jakarta Enterprise Edition.", "https://dc722jrlp2zu8.cloudfront.net/media/academy/course/jakarta-ee-card.jpg", 1);
INSERT INTO PRODUCTO (ID, NOMBRE, DESCRIPCION, IMAGEN, CATEGORIA_ID) VALUES (7, "Composer: Dependencias en PHP", "Aprende todo sobre Composer, la herramienta para PHP más extendida en la gestión de dependencias como librerías o paquetes ya sean de un tercero o un paquete de nuestro propio proyecto.", "https://dc722jrlp2zu8.cloudfront.net/media/academy/workshop/php-card.jpg", 1);
INSERT INTO PRODUCTO (ID, NOMBRE, DESCRIPCION, IMAGEN, CATEGORIA_ID) VALUES (8, "Fundamentos de PL/SQL", "En este curso de fundamentos de PL/SQL aprenderás a crear, modificar y detectar errores en los elementos PL/SQL desarrollados en una base de datos Oracle.", "https://dc722jrlp2zu8.cloudfront.net/media/academy/course/pl-sql-card.jpg", 2);
INSERT INTO PRODUCTO (ID, NOMBRE, DESCRIPCION, IMAGEN, CATEGORIA_ID) VALUES (9, "Oracle Performance: Estadisticas e indices", "Durante este taller veremos la recopilación de estadísticas e índices en bases de datos Oracle y como afectan al rendimiento de las mismas.", "https://dc722jrlp2zu8.cloudfront.net/media/academy/workshop/oracle-card.jpg", 2);
INSERT INTO PRODUCTO (ID, NOMBRE, DESCRIPCION, IMAGEN, CATEGORIA_ID) VALUES (10, "MongoDB", "Con este curso de MongoDB aprenderás a crear y gestionar bases de datos NoSQL utilizando MongoDB, la base de datos distribuida preferida por los desarrolladores de aplicaciones modernas, por su nivel de productividad y su facilidad de uso en la nube.", "https://dc722jrlp2zu8.cloudfront.net/media/academy/course/mongodb-card.jpg", 2);
INSERT INTO PRODUCTO (ID, NOMBRE, DESCRIPCION, IMAGEN, CATEGORIA_ID) VALUES (11, "Manipulacion de DataFrames con Pandas", "Realizando este curso aprenderás de una forma muy práctica a manipular, fusionar y transformar DataFrames para aplicar técnicas de análisis de datos, utilizando para ello la librería de Python Pandas.", "https://dc722jrlp2zu8.cloudfront.net/media/academy/course/pandas-sm.jpg", 3);
INSERT INTO PRODUCTO (ID, NOMBRE, DESCRIPCION, IMAGEN, CATEGORIA_ID) VALUES (12, "Curso de visualizacion de datos con SeaBorn", "Con este curso aprenderás de forma práctica a crear visualizaciones de datos utilizando Seaborn, una de las librerías de Python más conocidas y utilizadas en la actualidad.", "https://dc722jrlp2zu8.cloudfront.net/media/fbads-visualizacion-datos-seaborn.jpg", 3);
INSERT INTO PRODUCTO (ID, NOMBRE, DESCRIPCION, IMAGEN, CATEGORIA_ID) VALUES (13, "Curso de tratamiento de datos con Pandas y NumPy", "Con este curso aprenderás los fundamentos de Pandas y NumPy, las dos librerías más utilizadas en el ámbito Data Science para el tratamiento de datos, utilizando Python como lenguaje de programación.", "https://dc722jrlp2zu8.cloudfront.net/media/fbads-pandas-python.jpg", 3);
INSERT INTO PRODUCTO (ID, NOMBRE, DESCRIPCION, IMAGEN, CATEGORIA_ID) VALUES (14,